### ISSUE TITLE
README里的照片好像都挂了…

### ISSUE THREAD

**Issue by hoooJerry** [AngelKitty/review_the_national_post-graduate_entrance_examination#3]
小姐姐好！README里的照片无法正常显示哦，不知道是什么原因…
PS.公众号留言会看到嘛？

**Comment by AngelKitty** [comment]
@hoooJerry 可以正常显示哒，可能是你网络不太好的缘故QwQ，公众号留言一般隔几天会看一次，公众号有个很不好的设计就是。。。。48h消息无法回复，超过五天消息会自动清除，所以可能有时候看到也没办法回复了，希望理解！！！

**Comment by AngelKitty** [comment]
![屏幕快照 2019-11-01 下午2 56 53](https://user-images.githubusercontent.com/30405643/68007855-e30cea80-fcb7-11e9-9aa7-84fc9022c6ae.png)
![屏幕快照 2019-11-01 下午2 58 59](https://user-images.githubusercontent.com/30405643/68007965-3121ee00-fcb8-11e9-80bb-39ef5765ce29.png)
@hoooJerry 诺，写的都是相对路径的呢，不过最近上Github延迟都挺高的，可能是国内这墙越来越厚了吧QwQ

**Comment by AngelKitty** [comment]
当然如果在Github上留言的话，我基本上24h内会处理的
