### ISSUE TITLE
数学公式在暗黑模式下显示问题

### ISSUE THREAD

**Issue by JIeJaitt** [AngelKitty/review_the_national_post-graduate_entrance_examination#6]
博主你好，就是请问你提到的插入数学公式的办法在暗黑的模式或者背景下，显示效果一言难尽。请问有什么替代的解决办法嘛？

**Comment by gxw1** [comment]
发错人了吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月20日(周四) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [AngelKitty/review_the_national_post-graduate_entrance_examination] 数学公式在暗黑模式下显示问题 (Issue #6)




 
博主你好，就是请问你提到的插入数学公司的办法在暗黑模式或者背景下，显示效果一言难尽。请问有什么替代的解决办法嘛？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
